name: Create env and Test
on:
    push:
    pull_request:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: modiview
          environment-file: environment.yml
      - name: Activate environment
        run: |
          eval "$(conda shell.bash hook)"
          conda activate modiview
          conda list
      - name: Run tests
        run: |
          python -m unittest discover tests