name: Create env and Test
on:
    push:
    pull_request:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: modiview
          environment-file: environment.yml
      - name: Activate environment and test
        run: |
          conda activate modiview
          python -m unittest discover tests
