name: Create env and Test
on:
    push:
    pull_request:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: modiview
      - name: Run tests
        run: |
          python -m unittest discover tests